#!/bin/bash

session=0
if [[ $# -ge 1 ]] ; then
   session=$1
   shift
fi

tmux_run () {
   tmux -2uS  ~/.tmux.socket.$HOSTNAME.$session "$@"
}

tmux_run a -t $session
if [[ $? -eq 1 ]] ; then
   tmux_run new -s $session
fi
